#!/bin/bash

set -eu

die() {
  echo "$1" >&2
  exit 1
}

if [[ $# -ne 1 ]] || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then
  die "Usage:
  perl-install INSTALL_DIR      # install latest perl to INSTALL_DIR
  perl-install --print-version  # print latest perl version, and exit"
fi

PRINT_VERSION=NO
if [[ $1 = "--print-version" ]]; then
  PRINT_VERSION=YES
fi

_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
_ARCH=$(uname -m)
if [[ $_ARCH = x86_64 ]]; then
  _ARCH=amd64
fi
if [[ $_ARCH = aarch64 ]]; then
  _ARCH=arm64
fi

TAR_CMD=gtar
if ! type $TAR_CMD &>/dev/null; then
  TAR_CMD=tar
  if ! type $TAR_CMD &>/dev/null; then
    die 'Cannot find `tar` command'
  fi
fi

TAR_OPTION=xzf
TAR_SUFFIX=tar.gz
COMPRESS_TYPE=gz
if type xz &>/dev/null; then
  TAR_OPTION=xJf
  TAR_SUFFIX=tar.xz
  COMPRESS_TYPE=xz
fi

if type curl &>/dev/null; then
  HTTP_GET=curl
  HTTP_GET_OPTION='-fsSL'
elif type wget &>/dev/null; then
  HTTP_GET=wget
  HTTP_GET_OPTION='-q -O -'
else
  die 'Cannot find `curl` nor `wget`'
fi

LATEST_LINE=$($HTTP_GET $HTTP_GET_OPTION https://raw.githubusercontent.com/skaji/relocatable-perl/main/releases.csv | (\grep -m 1 ,$_OS,$_ARCH,$COMPRESS_TYPE; cat >/dev/null))
if [[ -z $LATEST_LINE ]]; then
  die "Failed to determine latest perl version"
fi

LATEST_VERSION=$(echo $LATEST_LINE | \cut -d, -f1)
LATEST_URL=$(echo $LATEST_LINE | \cut -d, -f5)
if [[ $PRINT_VERSION = "YES" ]]; then
  echo $LATEST_VERSION
  exit
fi

INSTALL_DIR=$1
if [[ -d $INSTALL_DIR ]]; then
  [[ -w $INSTALL_DIR ]] || die "You don't have write permission to $INSTALL_DIR"
else
  mkdir -p $INSTALL_DIR
  [[ -d $INSTALL_DIR ]] || die "Cannot create $INSTALL_DIR"
fi
ABS_INSTALL_DIR=$(cd $INSTALL_DIR &>/dev/null; pwd)

echo "Installing perl $LATEST_VERSION to $INSTALL_DIR, this may take a while..."

$HTTP_GET $HTTP_GET_OPTION $LATEST_URL | $TAR_CMD $TAR_OPTION - --strip-components 1 -C $INSTALL_DIR
if [[ ! -f $INSTALL_DIR/bin/perl ]]; then
  die "Failed to install perl"
fi

cat <<EOF
Successfully installed perl $LATEST_VERSION.
To use this perl, add the following line to ~/.bash_profile or ~/.zshrc:

  export PATH=$ABS_INSTALL_DIR/bin:\$PATH

EOF
