#!/bin/bash

set -eu

die() {
  echo "$1" >&2
  exit 1
}

if [[ $# -ne 1 ]] || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then
  die "Usage:
  perl-install INSTALL_DIR      # install latest perl to INSTALL_DIR
  perl-install --print-version  # print latest perl version, and exit"
fi

PRINT_VERSION=NO
if [[ $1 = "--print-version" ]]; then
  PRINT_VERSION=YES
fi

UNAME_SM=$(uname -sm)

if [[ $UNAME_SM = "Darwin x86_64" ]]; then
  ARCHNAME=darwin-2level
elif [[ $UNAME_SM = "Linux x86_64" ]]; then
  ARCHNAME=x86_64-linux
elif [[ $UNAME_SM = "Linux aarch64" ]]; then
  ARCHNAME=aarch64-linux
else
  die "Unsupported environment $UNAME_SM"
fi

if type curl &>/dev/null; then
  HTTP_GET=curl
  HTTP_GET_OPTION='-fsSL'
elif type wget &>/dev/null; then
  HTTP_GET=wget
  HTTP_GET_OPTION='-q -O -'
else
  die 'Cannot find `curl` nor `wget`'
fi

TAG=$($HTTP_GET $HTTP_GET_OPTION https://raw.githubusercontent.com/skaji/relocatable-perl/master/LATEST)
if [[ -z $TAG ]]; then
  die "Failed to determine latest perl version"
fi
if [[ $PRINT_VERSION = "YES" ]]; then
  echo $TAG
  exit
fi

TAR_CMD=gtar
if ! type $TAR_CMD &>/dev/null; then
  TAR_CMD=tar
  if ! type $TAR_CMD &>/dev/null; then
    die 'Cannot find `tar` command'
  fi
fi

TAR_OPTION=xzf
TAR_SUFFIX=tar.gz
if type xz &>/dev/null; then
  TAR_OPTION=xJf
  TAR_SUFFIX=tar.xz
fi

INSTALL_DIR=$1
if [[ -d $INSTALL_DIR ]]; then
  [[ -w $INSTALL_DIR ]] || die "You don't have write permission to $INSTALL_DIR"
else
  mkdir -p $INSTALL_DIR
  [[ -d $INSTALL_DIR ]] || die "Cannot create $INSTALL_DIR"
fi
ABS_INSTALL_DIR=$(cd $INSTALL_DIR &>/dev/null; pwd)

URL=https://github.com/skaji/relocatable-perl/releases/download/$TAG/perl-$ARCHNAME.$TAR_SUFFIX
echo "Installing perl $TAG to $INSTALL_DIR, this may take a while..."

$HTTP_GET $HTTP_GET_OPTION $URL | $TAR_CMD $TAR_OPTION - --strip-components 1 -C $INSTALL_DIR
if [[ ! -f $INSTALL_DIR/bin/perl ]]; then
  die "Failed to install perl"
fi

cat <<EOF
Successfully installed perl $TAG.
To use this perl, add the following line to ~/.bash_profile or ~/.zshrc:

  export PATH=$ABS_INSTALL_DIR/bin:\$PATH

EOF
