name: release

on:
  push:
    tags:
      - '*'

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg IMAGE=centos:centos6 -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_amd64_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: linux-amd64
          path: linux-amd64
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: docker buildx build --platform linux/arm64 --build-arg IMAGE=centos:centos7 -t skaji/relocatable-perl -f build/Dockerfile --load .
      - run: bash build/github-actions.sh linux_arm64_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: linux-arm64
          path: linux-arm64
  darwin-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: sw_vers
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-amd64
          path: darwin-amd64
  release:
    runs-on: ubuntu-latest
    needs:
      - linux-amd64
      - linux-arm64
      - darwin-amd64
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux-amd64
          path: linux-amd64
      - uses: actions/download-artifact@v2
        with:
          name: linux-arm64
          path: linux-arm64
      - uses: actions/download-artifact@v2
        with:
          name: darwin-amd64
          path: darwin-amd64
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-amd64/perl-linux-amd64.tar.gz
          asset_name: perl-linux-amd64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-amd64/perl-linux-amd64.tar.xz
          asset_name: perl-linux-amd64.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-arm64/perl-linux-arm64.tar.gz
          asset_name: perl-linux-arm64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-arm64/perl-linux-arm64.tar.xz
          asset_name: perl-linux-arm64.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: darwin-amd64/perl-darwin-amd64.tar.gz
          asset_name: perl-darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: darwin-amd64/perl-darwin-amd64.tar.xz
          asset_name: perl-darwin-amd64.tar.xz
          asset_content_type: application/x-xz
