name: release

on:
  push:
    tags:
      - '*'

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -o linux-amd64 -f build/Dockerfile .
      - uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: linux-amd64
  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: docker build -o linux-arm64 -f build/Dockerfile .
      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: linux-arm64
  darwin-amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          sw_vers
          system_profiler SPHardwareDataType
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: darwin-amd64
          path: darwin-amd64
  darwin-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          sw_vers
          system_profiler SPHardwareDataType
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: darwin-arm64
          path: darwin-arm64
  release:
    runs-on: ubuntu-latest
    needs:
      - linux-amd64
      - linux-arm64
      - darwin-amd64
      - darwin-arm64
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-amd64
          path: linux-amd64
      - uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: linux-arm64
      - uses: actions/download-artifact@v4
        with:
          name: darwin-amd64
          path: darwin-amd64
      - uses: actions/download-artifact@v4
        with:
          name: darwin-arm64
          path: darwin-arm64
      - name: create release and upload release assets
        run: gh release create --repo ${{ github.repository }} ${{ github.ref }} linux-*/*.gz linux-*/*.xz darwin-*/*.gz darwin-*/*.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
